id: misconfigured-concrete5

info:
  name: Misconfigured Concrete5
  author: pdteam
  severity: low
  description: Concrete5 CMS is misconfigured.
  metadata:
    max-request: 1
  tags: misconfig,concrete,cms

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2
    matchers:
      - type: word
        part: body
        words:
          - 'concrete5 has encountered an issue'
# digest: 4a0a00473045022100a5df656e056e9abd5480df11c7ad69d2b60cb682331f6b1df712fac958a1b1d002207c749a00fb2b8bad2fa92dee4a61aa34fe902996576686665d65d4d214172377:922c64590222798bb761d5b6d8e72950