id: application-yaml

info:
  name: application.yaml detection
  author: Cristi vlad (@cristivlad25)
  severity: info
  description: Finds Application YAML files which often contain sensitive information.
  metadata:
    max-request: 4
  tags: misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/app.yaml"
      - "{{BaseURL}}/app.yml"
      - "{{BaseURL}}/application.yaml"
      - "{{BaseURL}}/application.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        condition: or
        words:
          - "runtime:"
          - "spring:"
          - "datasource:"
          - "platform:"
          - "server:"
          - "job:"

      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
          - "!contains(tolower(body), '</h1>')"
          - "!contains(tolower(body), '</h2>')"
          - "!contains(tolower(body), '</h3>')"
          - "!contains(tolower(body), '<?xml')"
        condition: and
# digest: 4a0a0047304502206e87bf1b430705aa0b8e1eb3a56d815b944768c456830ce00e5908a4e37b0461022100841233b78c9755b2e8b24b6114d3bd06b9838641470eade3c0373b622804edfc:922c64590222798bb761d5b6d8e72950