<<<<<<< HEAD
id: awstats-config

name: AWStats config
severity: info

requests:
  - method: GET
    paths:
      - "HOSTNAME/awstats/"
      - "HOSTNAME/awstats.conf"

    patterns:
      - "AWSTATS CONFIGURE|Index of /awstats"
      - "MAIN SETUP SECTION|Parent Directory"
=======
id: awstats-config

info:
  name: AWStats config
  author: sheikhrishad
  severity: info
  tags: config,exposure,awstats

requests:
  - method: GET
    path:
      - "{{BaseURL}}/awstats/"
      - "{{BaseURL}}/awstats.conf"

    matchers:
      - type: word
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and
>>>>>>> c3808e48 (add new)
