id: awstats-config2

info:
  name: AWStats config
  author: sheikhrishad
  severity: info
  tags: config,exposure


requests:
  - raw:
      - |
        GET /awstats.conf HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers:
      - type: word
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and