id: azure-pipelines-exposed

info:
  name: Azure Pipelines Configuration File Disclosure
  author: DhiyaneshDk
  severity: medium
  description: Azure Pipelines internal critical file is disclosed.
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"azure-pipelines.yml"
  tags: config,exposure,azure,microsoft,cloud,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.azure-pipelines.yml"
      - "{{BaseURL}}/azure-pipelines.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "trigger:"
          - "pool:"
          - "variables:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a004830460221008b94c0b7ae5c2ca9bfae48435c7a1c090bbabe98b212d1d938b9dc3cf1e163e3022100814b1fc7dcfd68cfebf207a80a54fcdcd53de52cf07bcf2b83b59141ae8b9257:922c64590222798bb761d5b6d8e72950