id: bigip-config-utility

info:
  name: BIG-IP Configuration Utility detected
  author: dwisiswant0
  severity: info
  metadata:
    max-request: 3
  tags: tech,bigip

http:
  - method: GET
    path:
      - "{{BaseURL}}/tmui/login.jsp"
      - "{{BaseURL}}/tmui/tmui/login/welcome.jsp"

    matchers:
      - type: word
        words:
          - "Welcome to the BIG-IP"
          - "Configuration Utility"
        condition: and
        part: body

  - method: GET
    path:
      - "{{BaseURL}}/mgmt/tm/sys/management-ip"

    matchers:
      - type: word
        words:
          - "WWW-Authenticate: Basic realm"
          - "Enterprise Manager"
        condition: and
        part: header

      - type: word
        words:
          - "check your user-id and password and try again"
        part: body

# digest: 4b0a00483046022100f8ef3b159105fe202ca01534cbc95d96b1ee1d9b0797d2b7a69ea786fb069fe3022100e9031155ddc9c9cf28f645d6aa996070c76ba606d138037cccdea4348bdb04ee:922c64590222798bb761d5b6d8e72950
