name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install libpcap-dev
        run: sudo apt install libpcap-dev

      - name: Test
        run: go test .
        working-directory: .

      - name: Build
        run: go build .
        working-directory: .