id: wordpress-child-theme-configurator

info:
  name: Child Theme Configurator Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/child-theme-configurator/
  metadata:
    max-request: 1
    plugin_namespace: child-theme-configurator
    wpscan: https://wpscan.com/plugin/child-theme-configurator
  tags: tech,wordpress,wp-plugin,top-200

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/child-theme-configurator/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/child-theme-configurator.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

# digest: 490a00463044022067a67d622de2c769ac49698730fddbd373563e3159eac68af8e5c3ff1adc189f022041f60716719b103b09290fcf590e2d3cefd5b376f169a985f394c792c7bb340b:922c64590222798bb761d5b6d8e72950
