id: wordpress-child-theme-configurator

info:
  name: Child Theme Configurator Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/child-theme-configurator/
  metadata:
    plugin_namespace: child-theme-configurator
    wpscan: https://wpscan.com/plugin/child-theme-configurator
  tags: tech,wordpress,wp-plugin,top-200

http:
  - method: GET

    path:
      - "{{BaseURL}}/wp-content/plugins/child-theme-configurator/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/child-theme-configurator.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
# digest: 4b0a00483046022100f4c84272ca546cc2581916d9163a26cda420968f8df32a0196f93d258c0731fa022100daa70966ca5d335d87382881a19599ab6b2713876fcdd0c2bf0a9a416e3a1140:922c64590222798bb761d5b6d8e72950