id: cisco-network-config

info:
  name: Cisco System Network Configuration Page - Detect
  author: DhiyaneshDk
<<<<<<< HEAD
  severity: low
<<<<<<< HEAD
  reference:
    - https://www.exploit-db.com/ghdb/5430
  tags: config,exposure,cisco
=======
  severity: info
  description: Cisco System Network configuration page was detected. Page lists whole network configuration and internal logs of Cisco IP phones.
  reference:
    - https://www.exploit-db.com/ghdb/5430
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: exposure,cisco,edb,config
>>>>>>> 5d36d276 (add new stuff)
=======
  reference: https://www.exploit-db.com/ghdb/5430
  tags: config,exposure
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /CGI/Java/Serviceability?adapter=device.statistics.configuration HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Network Configuration"
        part: body

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
