id: cloud-config

info:
  name: Cloud Config File Exposure
  author: DhiyaneshDK,Hardik-Solanki
  severity: medium
  description: Cloud Config file is exposed.
  reference: https://www.exploit-db.com/ghdb/7959
  metadata:
    verified: true
    max-request: 3
    shodan-query: html:"cloud-config.yml"
  tags: exposure,cloud,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/cloud-config.yml"
      - "{{BaseURL}}/core-cloud-config.yml"
      - '{{BaseURL}}/cloud-config.txt'

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'ssh_authorized_keys'
          - '#cloud-config'
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022070154bbe8276ff9cf345a9568bbbc9e49cd546250ec749ff5a20b974e3c6418102204cdd06c2ebc4ce89c21bc5cb74169e53e0b747981e9e9492228ab3dfa4d7733a:922c64590222798bb761d5b6d8e72950