id: codeception-config

info:
  name: Codeception YAML Configuration File - Detect
  author: DhiyaneshDk
  severity: low
  description: Codeception YAML configuration file was detected.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"codeception.yml"
  tags: exposure,devops,codeception,config,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/codeception.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "paths:"
          - "settings:"
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a004730450220047fc0699cbd4601e89d7ab6696b668269053ecf08593f040203bf92ba027242022100ea3b90d2dc322e7c2f842d2855e5437e0177a7e4becef393ad46f85e7af405fb:922c64590222798bb761d5b6d8e72950
