id: composer-auth-json

info:
  name: Composer-auth Json File Disclosure
  author: DhiyaneshDK
  severity: low
  description: Composer Auth Josn file is disclosed.
  reference: https://www.exploit-db.com/ghdb/5768
  metadata:
    verified: true
    max-request: 2
    google-query: intext:"index of /" ".composer-auth.json"
  tags: exposure,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.composer-auth.json"
      - "{{BaseURL}}/vendor/webmozart/assert/.composer-auth.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'github-oauth'
          - 'github.com'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450220528743ede15c139c840411b47991f9329314ad0aa8fd771f5c4350b142857c9402210088cbdfa074686c7fe9c609ac549b2da1d7f6db05062eb47607952d9e03f81c61:922c64590222798bb761d5b6d8e72950