id: config-properties

info:
  name: Config Properties Exposure
  author: j4vaovo,DhiyaneshDK
  severity: high
  reference:
    - https://twitter.com/win3zz/status/1657624974851702784/photo/1
  metadata:
    verified: "true"
    max-request: 3
  tags: exposure,config,properties

http:
  - method: GET
    path:
      - "{{BaseURL}}/config.properties"
      - "{{BaseURL}}/config.properties.bak"
      - "{{BaseURL}}/ui_config.properties"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'jdbc:[a-z:]+://[A-Za-z0-9\.\-_:;=/@?,&]+'
          - '((?i)password|pwd|pass|secretkey)='
        condition: or

      - type: word
        part: header
        words:
          - "text/plain"
          - "bytes"
        condition: or

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200
