id: configure-dns-server

info:
  name: Configure DNS Server
  author: pussycat0x
  severity: info
  description: |
     The purpose DNs server is to perform the resolution of system hostnames to Internet Protocol (IP) addresses.
  reference: |
    https://docs.netgate.com/pfsense/en/latest/recipes/dns-over-tls.html
  metadata:
    verified: true
  tags: firewall,config,audit,pfsense,file

file:
  - extensions:
      - xml

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<dnsserver>"
        negative: true

      - type: word
        words:
          - "<pfsense>"
          - "<system>"
        condition: and
