id: cypress-web-config

info:
  name: Cypress Oxygen Configuration Page - Detect
  author: tess
  severity: info
  description: Cypress Oxygen configuration page was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"PendingInstallVZW - Web Page Configuration"
  tags: exposure,cypress,pendinginstallvzw,config

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'PendingInstallVZW - Web Page Configuration'
          - 'alt="Cypress Oxygen-3'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a0047304502205c8a648f9ecc81e7da54392b36064da2c9c8b7c20bedd1b7bd7fc0b08b6d6578022100a492126aca1d5b12014b218c20dd885fbd38efc802d8e0f57409e140625e7ca9:922c64590222798bb761d5b6d8e72950
