id: cypress-web-config

info:
<<<<<<< HEAD
<<<<<<< HEAD
  name: Cypress Oxygen Web Page Configuration
  author: tess
  severity: info
=======
  name: Cypress Oxygen Configuration Page - Detect
  author: tess
  severity: info
=======
  name: Cypress Oxygen Configuration Page - Detect
  author: tess
  severity: info
>>>>>>> 18ddf72b (add new stuff)
  description: Cypress Oxygen configuration page was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
<<<<<<< HEAD
>>>>>>> 5d36d276 (add new stuff)
=======
>>>>>>> 18ddf72b (add new stuff)
  metadata:
    verified: true
    shodan-query: http.title:"PendingInstallVZW - Web Page Configuration"
  tags: exposure,cypress,pendinginstallvzw,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'PendingInstallVZW - Web Page Configuration'
          - 'alt="Cypress Oxygen-3'
        condition: and

      - type: status
        status:
          - 200
<<<<<<< HEAD
<<<<<<< HEAD
=======

# Enhanced by md on 2023/02/09
>>>>>>> 5d36d276 (add new stuff)
=======

# Enhanced by md on 2023/02/09
>>>>>>> 18ddf72b (add new stuff)
