id: dockercfg-config1

info:
  name: Detect .dockercfg
  author: geeknik
  severity: high
  description: Docker registry authentication data
  tags: docker,exposure,config


requests:
  - raw:
      - |
        GET /.dockercfg HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:

      - type: word
        words:
          - '"email":'
          - '"auth":'
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
