id: ftpconfig

info:
  name: Atom remote-ssh ftpconfig Exposure
  author: geeknik,DhiyaneshDK
  severity: high
  description: Created by remote-ssh for Atom, contains SFTP/SSH server details and credentials
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:ftpconfig
  tags: atom,ftp,config,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.ftpconfig"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"protocol":'
          - '"host":'
          - '"user":'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a00473045022038b25462e3325f19569cd795578decf6a4d9a9faa965793574ad334e6058660f022100fd1c9874ca616332e03cdca6a9ce02e6d3f92e3503a3627076e6e8025030c876:922c64590222798bb761d5b6d8e72950
