id: gcloud-config-default

info:
  name: Google Cloud Default Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Google Cloud default configuration was detected.
  reference: https://cloud.google.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"access_tokens.db"
  tags: google,cloud,devops,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/configurations/config_default"
      - "{{BaseURL}}/.config/gcloud/configurations/config_default"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[core]'
          - 'account'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100d0a910249cc49a3cbe12502c6d9459a40ddc5a823105e8eae01dea16d4c8fe22022038555393022f94dbcadd44f028fa0b0b903b6e2daa290f2995a6459ca56c6d5e:922c64590222798bb761d5b6d8e72950
