id: golangci-config

info:
  name: GolangCI-Lint Configuration File - Detect
  author: Hardik-Solanki
  severity: info
  description: GolangCI-Lint configuration file was detected.
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
    - https://golangci-lint.run/usage/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 4
    github-query: filename:golangci.yml
  tags: exposure,golang,devops,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/.golangci.yml"
      - "{{BaseURL}}/.golangci.yaml"
      - "{{BaseURL}}/.golangci.toml"
      - "{{BaseURL}}/.golangci.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'linters:'
          - 'linters-settings:'
        condition: and

      - type: status
        status:
          - 200

# digest: 490a0046304402205d5aa6bf2de57b26125d3757839c5c19d7302b22861b7dc8c947d2de76883c50022005328b1b52b568178c7327e8e3d42b883ae76bb9104f4acf3930c95a72adc787:922c64590222798bb761d5b6d8e72950
