id: honeywell-scada-config

info:
<<<<<<< HEAD
  name: Honeywell Scada Configuration File - Detect
  author: alperenkesk
  severity: low
<<<<<<< HEAD
=======
  description: Honeywell Scada configuration file was detected. The downloaded file opens with the file name and contains critical information about the destination address.
>>>>>>> 5d36d276 (add new stuff)
  reference:
    - https://www.exploit-db.com/exploits/44734
  tags: scada,config,exposure,edb
=======
  name: Honeywell Scada System – Information Disclosure
  author: alperenkesk
  severity: low
  reference: https://www.exploit-db.com/exploits/44734
  tags: scada,config,exposure
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /web_caps/webCapsConfig HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DeviceSubClass"
          - "IPAddress"
        condition: and

      - type: status
        status:
<<<<<<< HEAD
          - 200

# Enhanced by md on 2023/02/09
=======
          - 200
>>>>>>> 18ddf72b (add new stuff)
