id: jeecg-boot-swagger

info:
  name: Jeecg Boot Swagger Bootstrap UI - Detect
  author: ritikchaddha
  severity: info
  metadata:
    max-req: 1
    verified: "true"
    shodan-query: title:"Jeecg-Boot"
    fofa-query: title="JeecgBoot 企业级低代码平台"
  tags: jeecg,swagger,detect,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/jeecg-boot/"

    matchers:
      - type: word
        part: body
        words:
          - "<title>Swagger-Bootstrap-UI</title>"
