id: jeecg-boot-swagger

info:
  name: Jeecg Boot Swagger Bootstrap UI - Detect
  author: ritikchaddha
  severity: info
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Jeecg-Boot"
    fofa-query: title="JeecgBoot 企业级低代码平台"
  tags: jeecg,swagger,detect,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/jeecg-boot/"

    matchers:
      - type: word
        part: body
        words:
          - "<title>Swagger-Bootstrap-UI</title>"

# digest: 4a0a00473045022100de7182a29ddaa4ada36c16ec7c8947efc1615882cb49608eb5bb9a60a0be61f402206cd588a77627e3a229d2899915e1e3e2a2fa62990fb985c4093480b74b7d64de:922c64590222798bb761d5b6d8e72950
