id: joomla-config-dist-file

info:
<<<<<<< HEAD
<<<<<<< HEAD
  name: Joomla! Config Dist File
  author: oppsec
  severity: low
  description: configuration.php-dist is a file created by Joomla! to save Joomla settings.
=======
  name: Joomla! Configuration File - Detect
  author: oppsec
  severity: low
  description: Joomla! configuration.php-dist file was detected.
>>>>>>> 5d36d276 (add new stuff)
  tags: config,exposure,joomla
=======
  name: Joomla Config Dist File
  author: oppsec
  severity: low
  description: configuration.php-dist is a file created by Joomla to save Joomla settings.
  tags: config,exposure
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /configuration.php-dist HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Joomla"
          - "JConfig"
          - "@package"
        condition: and

      - type: word
        words:
          - "text/plain"
        part: header

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
