id: joomla-config-dist-file

info:
<<<<<<< HEAD
  name: Joomla! Config Dist File
  author: oppsec
  severity: low
  description: configuration.php-dist is a file created by Joomla! to save Joomla settings.
=======
  name: Joomla! Configuration File - Detect
  author: oppsec
  severity: low
  description: Joomla! configuration.php-dist file was detected.
>>>>>>> 5d36d276 (add new stuff)
  tags: config,exposure,joomla

requests:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.php-dist"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Joomla"
          - "JConfig"
          - "@package"
        condition: and

      - type: word
        words:
          - "text/plain"
        part: header

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
