id: keycloak-openid-config

info:
  name: Keycloak OpenID Configuration - Detect
  author: rodnt
  severity: info
  description: Keycloak Openid configuration information was detected.
  reference:
    - https://issues.jboss.org/browse/KEYCLOAK-571
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: keycloak,config
  metadata:
    max-request: 2

http:
  - method: GET
    path:
      - "{{BaseURL}}/.well-known/openid-configuration"
      - "{{BaseURL}}/auth/realms/master/.well-known/openid-configuration"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'issuer'
          - 'authorization_endpoint'
          - 'token_endpoint'
          - 'userinfo_endpoint'
          - 'jwks_uri'
        condition: and

# Enhanced by mp on 2023/02/05