id: kingcomposer-d41d8cd98f00b204e9800998ecf8427e

info:
  name: "Page Builder: KingComposer < 2.9.4 - Authorization Bypass due to Improper Access Control"
  author: topscoder
  severity: high
  description: "The Page Builder: KingComposer plugin for WordPress is vulnerable to authorization bypass in versions up to, and including, 2.9.3. This is due to a security nonce being leaked in the '/wp-admin/index.php' page. This makes it possible for authenticated attackers to change arbitrary WordPress options, delete arbitrary files/folders, and inject arbitrary content."
  reference:

  classification:
    cvss-metrics:
    cvss-score:
    cve-id:
  metadata:
    fofa-query: "wp-content/plugins/kingcomposer/"
    google-query: inurl:"/wp-content/plugins/kingcomposer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,kingcomposer,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/kingcomposer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "kingcomposer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<=  2.9.3')