id: kubernetes-kustomization-disclosure

info:
  name: Kubernetes Kustomize Configuration - Detect
  author: dhiyaneshDk
  severity: medium
<<<<<<< HEAD
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
<<<<<<< HEAD
=======
  description: Kubernetes Kustomize configuration was detected.
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
>>>>>>> 5d36d276 (add new stuff)
  tags: exposure,config,kubernetes
=======
  tags: exposure,config
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /kustomization.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - "apiVersion:"
          - "resources:"
          - "namespace:"
          - "commonLabels:"
          - "Kustomization"

      - type: word
        part: body
        condition: or
        words:
          - "yaml"
          - "yml"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
