id: magento-config1
info:
  name: Magento Config Disclosure
  author: geeknik
  severity: medium
  tags: config,exposure,magento


requests:
  - raw:
      - |
        GET /app/etc/local.xml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/xml"
        part: header

      - type: word
        words:
          - "Magento"
        part: body