id: manageengine-applications-manager

info:
<<<<<<< HEAD
  name: ZOHO ManageEngine Applications Manager
  author: dhiyaneshDK
  severity: info
<<<<<<< HEAD
=======
  name: ZOHO ManageEngine Applications Manager Panel - Detected
  author: dhiyaneshDK
  severity: info
  description: ZOHO ManageEngine panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
>>>>>>> 5d36d276 (add new stuff)
=======
  reference: https://fofa.so/result?qbase64=YXBwPSJaT0hPLU1hbmFnZUVuZ2luZS1BcHBsaWNhdGlvbnMtTWFuYWdlciI%3D
>>>>>>> 18ddf72b (add new stuff)
  tags: panel,zoho,manageengine

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /index.do HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'

      - type: status
        status:
          - 200
<<<<<<< HEAD
=======

# Enhanced by mp on 2023/01/29
>>>>>>> 5d36d276 (add new stuff)
