id: manageengine-network-config

info:
  name: Zoho ManageEngine Network Configuration Manager Panel - Detect
  author: righettod
  severity: info
  description: ZOHO ManageEngine Network Configuration Manager was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    vendor: zohocorp
    product: manageengine_network_configuration_manager
    shodan-query: http.title:"Network Configuration Manager"
  tags: panel,zoho,manageengine

http:
  - method: GET
    path:
      - '{{BaseURL}}/apiclient/ember/Login.jsp'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Network Configuration Manager'
          - 'https://www.manageengine.com'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a0048304602210081dba7ac3da573dffe7bfaf323bbbc57c4354ae0afa39feb3ec1ea608f1ac4190221008ef0856eb69903557ce11925b968b725ef69d8e81816f6a1403577304fc492df:922c64590222798bb761d5b6d8e72950