id: manageengine-applications-manager

info:
  name: ZOHO ManageEngine Applications Manager Panel - Detected
  author: dhiyaneshDK
  severity: info
  description: ZOHO ManageEngine panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
    vendor: zohocorp
    product: manageengine_applications_manager
  tags: panel,zoho,manageengine

http:
  - method: GET
    path:
      - '{{BaseURL}}/index.do'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100f9d25f2b9c3af50e6f9cd29d880d06f723c4752b6c3333c4c0c26f9dddea5efb02206ed63495ebd0cdb005cd8e83afa6f2b36444564ee322d6a3f1cdac2fa3a1b74d:922c64590222798bb761d5b6d8e72950