id: netbeans-config

info:
  name: Netbeans Config - Detect
  author: sbani
  severity: info
  description: Netbeans configuration information was detected.
  reference:
    - https://netbeans.apache.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: netbeans,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/nbproject/project.properties"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?mi)^src.dir="
          - "(?mi)^build.[a-zA-Z]+="
          - "(?mi)^jar.[a-zA-Z]+="
        condition: or

      - type: status
        status:
          - 200

# digest: 4a0a0047304502210089724173f7c902d257be6779339ec8a5f6153676da064854b715339792e190a80220536aae8e55fb856fe35eb989e89e677508ba0b7c04531e2928a3db6609b24840:922c64590222798bb761d5b6d8e72950
