id: nginx-config

info:
<<<<<<< HEAD
  name: Nginx Config file disclosure
  author: sheikhrishad
  severity: info
=======
  name: Nginx Config - Detect
  author: sheikhrishad,geeknik
  severity: info
  description: Nginx configuration information was detected.
  reference:
    - https://nginx.org/en/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
>>>>>>> 5d36d276 (add new stuff)
  tags: config,exposure,nginx

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /nginx.conf HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "server"
          - "listen"
          - "server_name"
        condition: and

      - type: status
        status:
<<<<<<< HEAD
          - 200
<<<<<<< HEAD
=======

# Enhanced by mp on 2023/02/05
>>>>>>> 5d36d276 (add new stuff)
=======
          - 200
>>>>>>> 18ddf72b (add new stuff)
