id: nginx-config

info:
<<<<<<< HEAD
  name: Nginx Config file disclosure
  author: sheikhrishad,geeknik
  severity: info
=======
  name: Nginx Config - Detect
  author: sheikhrishad,geeknik
  severity: info
  description: Nginx configuration information was detected.
  reference:
    - https://nginx.org/en/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
>>>>>>> 5d36d276 (add new stuff)
  tags: config,exposure,nginx

requests:
  - method: GET
    path:
      - "{{BaseURL}}/nginx.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "html>"
        negative: true
      - type: word
        words:
          - "server"
          - "listen"
          - "server_name"
        condition: and

      - type: status
        status:
          - 200
<<<<<<< HEAD
=======

# Enhanced by mp on 2023/02/05
>>>>>>> 5d36d276 (add new stuff)
