id: openapi

info:
<<<<<<< HEAD
  name: OpenAPI - Detect
=======
  name: OpenAPI
>>>>>>> 18ddf72b (add new stuff)
  author: pdteam,ynnirc
  severity: info
  description: OpenAPI was detected.
  reference:
    - https://www.openapis.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: exposure,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/openapi.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
<<<<<<< HEAD
<<<<<<< HEAD
          - application/openapi+json
        part: header
      - type: word
        words:
          - openapi
          - paths
        condition: and
=======
          - openapi
          - paths
        condition: and
=======
          - openapi
          - paths
        condition: and
>>>>>>> 18ddf72b (add new stuff)

      - type: word
        part: header
        words:
          - application/openapi+json
          - application/json
        condition: or

<<<<<<< HEAD
>>>>>>> 5d36d276 (add new stuff)
=======
>>>>>>> 18ddf72b (add new stuff)
      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
