id: owncloud-config

info:
  name: owncloud Config - Detect
  severity: info
<<<<<<< HEAD
<<<<<<< HEAD
=======
  author: Mahendra Purbia (Mah3Sec_)
  description: owncloud configuration information was detected.
  reference:
    - https://owncloud.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,exposure
>>>>>>> 5d36d276 (add new stuff)
=======
  tags: config,exposure
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /owncloud/config/ HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Index of'
          - 'owncloud/config'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
