id: php-composer-binary

info:
  name: PHP Composer Binary - Exposure
  author: mayank_pandey01
  severity: info
  description: |
    This Nuclei template checks if the specified endpoints have publically accessible PHP Composer Binary.
  remediation: |
    Restrict access to the PHP Composer binary by implementing proper access controls and permissions.
  metadata:
    max-request: 1
    verified: true
  tags: php,composer,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/composer"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "/usr/bin/env php"
          - "<?php"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100a085f102ec0d0a64d870c018afbd99bdd7cf5f977494c4b3744a85de701c14cd022040e626168d9d5c6408c4a0323613c366714e937aafe0d12fa44d2cf66f4cd8fd:922c64590222798bb761d5b6d8e72950