id: production-logs

info:
  name: Discover production log files
  author: geeknik
  severity: info
  metadata:
    max-request: 3
  tags: exposure,logs,rails

http:
  - method: GET
    path:
      - "{{BaseURL}}/log/production.log"
      - "{{BaseURL}}/logs/production.log"
      - "{{BaseURL}}/production.log"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Connecting to database specified by database.yml"
          - "Started GET"
        condition: and

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

    extractors:
      - type: regex
        name: last_modified
        part: header
        regex:
          - 'Last-Modified:.*'

# digest: 4a0a00473045022100a38713583e2a55ad0343c4115da819838f3f4cd0ebcef23f58e7a5541c1e150302202cd2dd72c9f7bcc7dbbd00619a14637be21dfd8cc1950f1d7cd9b035ddca9d8f:922c64590222798bb761d5b6d8e72950
