id: producthunt

info:
  name: Producthunt
  author: dwisiswant0
  severity: info
  tags: osint,osint-business,producthunt

self-contained: true
requests:
  - method: GET
    path:
      - "https://www.producthunt.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "s profile on Product Hunt"
