id: product-delivery-date-for-woocommerce-lite-01b0dc549cd6090a0b5c7ae2680543c9

info:
  name: >
    Product Delivery Date for WooCommerce – Lite <= 2.7.2 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/71a45950-bae1-4b14-8935-251b8713c570?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-delivery-date-for-woocommerce-lite/"
    google-query: inurl:"/wp-content/plugins/product-delivery-date-for-woocommerce-lite/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-delivery-date-for-woocommerce-lite,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-delivery-date-for-woocommerce-lite/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-delivery-date-for-woocommerce-lite"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.7.2')