id: prometheus-metrics

info:
  name: Prometheus Metrics - Detect
  author: dhiyaneshDK,philippedelteil
  severity: medium
  description: Prometheus metrics page was detected.
  reference:
    - https://github.com/prometheus/prometheus
    - https://hackerone.com/reports/1026196
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: exposure,prometheus,hackerone,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"
      - "{{BaseURL}}/api/metrics"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'cpu_seconds_total'
          - 'http_request_duration_seconds'
          - 'process_virtual_memory_bytes'
          - 'process_start_time_seconds'
        condition: or

      - type: word
        part: body
        words:
          - "lvm_"
        negative: true

      - type: status
        status:
          - 200

# digest: 4a0a0047304502206a91f07c6ef932dad78722633bd4966ef49dfec12dad50dd6e67b7f36e7c376d022100d3912261718bbd4bb5b66da39959f5bf3a5c3b1f9f9b2b87a3608cf134494a87:922c64590222798bb761d5b6d8e72950
