id: prometheus-exposed-panel

info:
<<<<<<< HEAD
  name: Prometheus.io exposed panel
  author: organiccrap
  severity: low
=======
  name: Prometheus Panel - Detect
  author: organiccrap
  severity: info
  description: Prometheus panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
>>>>>>> 5d36d276 (add new stuff)
  tags: panel,prometheus

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /graph HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
<<<<<<< HEAD
          - '<title>Prometheus Time Series Collection and Processing Server</title>'
=======
          - '<title>Prometheus Time Series Collection and Processing Server</title>'

# Enhanced by md on 2022/12/06
>>>>>>> 5d36d276 (add new stuff)
