id: prometheus-exporter-detect
info:
  name: Prometheus exporter detect
  author: jarijaas
  severity: info
  description: Prometheus exporter detector
  tags: panel
  reference: https://github.com/prometheus/prometheus/wiki/Default-port-allocations

requests:
<<<<<<< HEAD
  - method: GET
    path:
      - "{{BaseURL}}"
<<<<<<< HEAD
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
=======

>>>>>>> 5d36d276 (add new stuff)
=======
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET / HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
>>>>>>> 18ddf72b (add new stuff)
    matchers-condition: and
    matchers:
      - type: word
        words:
          - Exporter # Exporters have "Exporter" in the page title (e.g, Node Exporter, Bind Exporter and so on)
          - /metrics
<<<<<<< HEAD
        condition: and
<<<<<<< HEAD
=======

>>>>>>> 5d36d276 (add new stuff)
    extractors: # Extract exporter name
      - type: regex
        part: body
        name: exporter_name
        group: 1
        regex:
          - "<title>(.*?)</title>"
=======
        condition: and
>>>>>>> 18ddf72b (add new stuff)
