id: rollup-js-config

info:
  name: Rollup.js Configuration - Detect
  author: DhiyaneshDK
  severity: info
  description: Rollup configuration was detected.
  reference:
    - https://rollup.docschina.org/guide/en/#configuration-files
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"rollup.config.js"
  tags: exposure,devops,cicd,rollupjs

http:
  - method: GET
    path:
      - '{{BaseURL}}/rollup.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'export default ['
          - 'input:'
        condition: and

      - type: status
        status:
          - 200

# digest: 4b0a0048304602210097523c84649c8721ae48e8af123c170b9d2a886da70a019ecc9cc4de97a1649d022100c3bfee17b7e987b071417bad1fa83b00451f12deb4cdffc689fe3b81f56c0178:922c64590222798bb761d5b6d8e72950
