id: rubocop-config

info:
  name: Rubocop Configuration - Detect
  author: DhiyaneshDk
  severity: info
  description: Rubocop configuration information was detected.
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
    - https://github.com/rubocop/rubocop
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"rubocop.yml"
  tags: exposure,files,config,ruby

http:
  - method: GET
    path:
      - '{{BaseURL}}/.rubocop.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "AllCops:"
          - "Include:"
          - "Exclude:"
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100bdff48f210d9f69bc48242af4413cac4b3591b7e033f31ca13d71516c31fa1800220563f6c43af54d64099634c3d0550eb4e9a9cc4b7a9bf6aabaa1a165de9c64881:922c64590222798bb761d5b6d8e72950
