id: saltstack-config-panel

info:
<<<<<<< HEAD
<<<<<<< HEAD
  name: SaltStack Config Panel
=======
  name: SaltStack Config Panel - Detect
>>>>>>> 5d36d276 (add new stuff)
=======
  name: SaltStack Config Panel - Detect
>>>>>>> 18ddf72b (add new stuff)
  author: pussycat0x
  severity: info
  description: |
    SaltStack config panel was detected.
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 18ddf72b (add new stuff)
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
<<<<<<< HEAD
>>>>>>> 5d36d276 (add new stuff)
=======
>>>>>>> 18ddf72b (add new stuff)
  metadata:
    verified: true
    shodan-query: title:"SaltStack Config"
  tags: panel,vmware,login,saltstack

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "SaltStack Config"

      - type: status
        status:
          - 200
<<<<<<< HEAD
<<<<<<< HEAD
=======

# Enhanced by cs 01/26/2023
>>>>>>> 5d36d276 (add new stuff)
=======

# Enhanced by cs 01/26/2023
>>>>>>> 18ddf72b (add new stuff)
