id: samba-config

info:
  name: Samba Config - Detect
  author: sheikhrishad
  severity: info
<<<<<<< HEAD
  description: Samba configuration information was detected.
  reference: https://www.samba.org/samba/docs/using_samba/ch06.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: config,exposure,smb,samba
=======
  tags: config,exposure,smb
>>>>>>> 18ddf72b (add new stuff)

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /smb.conf HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "configuration file"
          - "samba"
        condition: and

      - type: status
        status:
<<<<<<< HEAD
          - 200

# Enhanced by mp on 2023/02/05
=======
          - 200
>>>>>>> 18ddf72b (add new stuff)
