id: wordpress-sg-security

info:
  name: Security Optimizer – The All-In-One WordPress Protection Plugin Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/sg-security/
  metadata:
    max-request: 1
    plugin_namespace: sg-security
    wpscan: https://wpscan.com/plugin/sg-security
  tags: tech,wordpress,wp-plugin,top-100,top-200

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/sg-security/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/sg-security.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

# digest: 4a0a0047304502210080f09110ae3b20b0d892459227983e98d3657d0588c5b0683ed15c7fe6505378022062716de38046c7c5bbef95332f92610dd71b17714d18d76d6fd9cce9df4a3219:922c64590222798bb761d5b6d8e72950
