id: sonic-wall-application

info:
  name: SonicWall Appliance Management Console Login Panel - Detect
  author: DhiyaneshDk,Tess
  severity: info
  description: SonicWall Appliance Management Console login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Appliance Management Console Login"
  tags: panel,sonicwall,login

http:
  - method: GET
    path:
      - "{{BaseURL}}/login.do"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Appliance Management Console Login</title>'

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100ef1dac4616193f359e3d72e47d84e4e238808c96ca066ff82c75dd8368021e4202201b945b2a75bb387a9a60e9dbf5f2aa25e3e8c598021a966858086e8eeaf151ab:922c64590222798bb761d5b6d8e72950
