id: swagger-api

info:
  name: Public Swagger API
  author: pdteam,c-sh0
  severity: info
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}/api_docs"
      - "{{BaseURL}}/api/docs/"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/api/apidocs"
      - "{{BaseURL}}/api/swagger"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/api/api-docs"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/api/api-docs"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}/swagger-ui.js"
      - "{{BaseURL}}/api/_swagger_/"
      - "{{BaseURL}}/api/index.html"
      - "{{BaseURL}}/api/swagger.yml"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/api/v2/api-docs"
      - "{{BaseURL}}/api/v1/api-docs"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/swagger/ui/index"
      - "{{BaseURL}}/api/__swagger__/"
      - "{{BaseURL}}/api/swagger.json"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api/swagger/ui/index"
      - "{{BaseURL}}/api/swagger_doc.json"
      - "{{BaseURL}}/api-docs/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/swagger-resources"
      - "{{BaseURL}}/api/spec/swagger.yaml"
      - "{{BaseURL}}/swagger/swagger-ui.js"
      - "{{BaseURL}}/api/spec/swagger.json"
      - "{{BaseURL}}/api/swagger/index.html"
      - "{{BaseURL}}/api/swagger-ui/api-docs"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/swagger/v1/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/api/apidocs/swagger.json"
      - "{{BaseURL}}/swagger/ui/swagger-ui.js"
      - "{{BaseURL}}/api/apidocs/swagger.yaml"
      - "{{BaseURL}}/swagger-ui/swagger-ui.js"
      - "{{BaseURL}}/api/api-docs/swagger.json"
      - "{{BaseURL}}/api/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/swagger/static/index.html"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "**token**:"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
