id: tcpconfig

info:
  name: TCP Config Information Exposed
  author: dhiyaneshDK
  severity: low
  reference:
    - https://www.exploit-db.com/ghdb/6782
<<<<<<< HEAD
  tags: logs,config
=======
  tags: config,edb,logs
>>>>>>> 5d36d276 (add new stuff)

requests:
  - method: GET
    path:
      - "{{BaseURL}}/tcpconfig.html"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "TCP/IP Configuration"

      - type: status
        status:
          - 200
