id: web-config

info:
  name: Web Config file
  author: Yash Anand @yashanand155,DhiyaneshDK
  severity: info
  reference: https://github.com/imhunterand/ApachSAL/blob/main/assets/exploits.json
  tags: config,exposure

requests:
<<<<<<< HEAD
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
=======
  - method: GET
    path:
      - '{{BaseURL}}/web.config'
      - '{{BaseURL}}/../../web.config'
>>>>>>> 5d36d276 (add new stuff)

    raw:
      - |
        GET /web.config HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - <configuration>
          - <system.webServer>
        condition: and

      - type: status
        status:
          - 200
