id: wgetrc-config

info:
  name: Wgetrc Configuration File - Detect
  author: DhiyaneshDK
  severity: info
  description: Wgetrc configuration file was detected.
  reference: https://www.gnu.org/software/wget/manual/html_node/Wgetrc-Commands.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:".wgetrc"
  tags: devops,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/wgetrc"
      - "{{BaseURL}}/.wgetrc"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '/etc/wgetrc'
          - 'wget.info'

      - type: word
        part: header
        words:
          - 'application/octet-stream'

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100d4a7dc542622416c4d0efad305d40c627c640e2d0e343c2aa60eda8acc903dc7022002cf9a4d4164a24f59d9711b4b3ad99d2d657464e6ef9a14d622ac1bdf2b72ac:922c64590222798bb761d5b6d8e72950
