id: xampp-environment-variables

info:
  name: XAMPP Environment Variables Exposure
  author: melbadry9,DhiyaneshDK
  severity: low
  description: printenv.pl file is exposed in XAMPP leaking environment variables.
  metadata:
    max-request: 1
  tags: exposure,xampp,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/printenv.pl"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<TITLE>Environment Variables</TITLE>"
          - "Environment Variables:"
        condition: and

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100ba84367376831e8b589332c1195517f95a26bdd9bc8d80270361d015f1b3bdf602203c7f8bae48ce9f9661d6ef17f8dea0debd3c6218e6875bb2dd04204a832de77b:922c64590222798bb761d5b6d8e72950