id: zend-config-file

info:
  name: Zend Configuration File
<<<<<<< HEAD
<<<<<<< HEAD
  author: pdteam,geeknik
=======
  author: pdteam,geeknik,Akokonunes
>>>>>>> 5d36d276 (add new stuff)
=======
  author: pdteam
>>>>>>> 18ddf72b (add new stuff)
  severity: high
  tags: config,exposure,zend,php

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /application/configs/application.ini HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
<<<<<<< HEAD
      - type: word
        words:
          - "resources.db.params.password"
<<<<<<< HEAD
          - "resources.db.params.username"
=======
      - type: regex
        regex:
          - "db.*(.password).*="
          - "db.*(.username).*="
>>>>>>> 5d36d276 (add new stuff)
        condition: and
=======
>>>>>>> 18ddf72b (add new stuff)

      - type: word
        words:
          - "text/plain"
        part: header

      - type: status
        status:
          - 200
