http:
- extractors:
  - group: 1
    name: version
    part: body
    regex:
    - (?mi)Stable tag:\s*([0-9.]+)
    type: regex
  matchers:
  - status:
    - 200
    type: status
  - part: body
    type: word
    words:
    - easy-php-settings
  - dsl:
    - compare_versions(version, '<= 1.0.4')
    type: dsl
  matchers-condition: and
  max-redirects: 3
  method: GET
  path:
  - '{{BaseURL}}/wp-content/plugins/easy-php-settings/readme.txt'
  redirects: true
id: easy_php_settings-f9927487-99fb-46d9-a208-f19e0a371267
info:
  author: topscoder
  classification:
    cve-id: null
    cvss-metrics: null
    cvss-score: null
  description: ''
  metadata:
    fofa-query: wp-content/plugins/easy-php-settings/
    google-query: inurl:"/wp-content/plugins/easy-php-settings/"
    shodan-query: http.html:"wp-content/plugins/easy-php-settings/"
  name: 'Easy PHP Settings <= 1.0.4 - Authenticated (Administrator+) PHP Code Injection
    via ''wp_memory_limit'' Setting

    '
  reference:
  - https://github.com/topscoder/nuclei-wordfence-cve
  - https://www.wordfence.com/threat-intel/vulnerabilities/id/f9927487-99fb-46d9-a208-f19e0a371267?source=api-scan
  severity: low
  tags: cve,wordpress,wp-plugin,easy-php-settings,low,candidate
