id: amazing-service-box-visual-composer-addons-e8738b0b532e048b6483f5bdddcea665

info:
  name: >
    Amazing service box Addons For WPBakery Page Builder <= 2.0.0 - Authenticated (Author+) Stored Cross-Site Scripting via SVG File Upload
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/a4f6ce4d-6ca5-4a62-ae84-9dd190fc0392?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/amazing-service-box-visual-composer-addons/"
    google-query: inurl:"/wp-content/plugins/amazing-service-box-visual-composer-addons/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,amazing-service-box-visual-composer-addons,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/amazing-service-box-visual-composer-addons/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "amazing-service-box-visual-composer-addons"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.0.0')