id: aws-xray-application

info:
  name: AWS X-Ray Sample Application
  author: DhiyaneshDk
  severity: info
  description: AWS X-Ray is a service that helps developers analyze and debug distributed applications.
  reference:
    - https://www.facebook.com/ExWareLabs/photos/a.361854183878462/5566269380103557/
  metadata:
    max-request: 1
    verified: true
    shodan-query: title:"AWS X-Ray Sample Application"
  tags: misconfig,aws,x-ray,amazon

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>AWS X-Ray Sample Application</title>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
