id: azon-addon-js-composer-ca7e378cfd6c05e0f4fa65047350c357

info:
  name: >
    Amazon Affiliates Addon for WPBakery Page Builder (formerly Visual Composer) <= 1.2 - Authenticated (Subscriber+) SQL Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/7ea10a95-c24b-49ae-8a70-317fe04590bf?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/azon-addon-js-composer/"
    google-query: inurl:"/wp-content/plugins/azon-addon-js-composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,azon-addon-js-composer,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/azon-addon-js-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "azon-addon-js-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2')