id: exposed-ingress-nginx-admission

info:
  name: Publicly exposed Ingress NGINX Admission
  author: Wiz research
  severity: high
  description: Ingress Nginx admission controller endpoint should not be exposed
  metadata:
    max-request: 1
  tags: ssl,tls

ssl:
  - address: "{{Host}}:{{Port}}"

    matchers:
      - type: dsl
        dsl:
          - 'contains(issuer_org, "nil1")'
          - 'contains(subject_org, "nil2")'
          - 'contains(subject_an, "nginx")'
        condition: and

    extractors:
      - type: json
        name: issuer_org
        json:
            - ".issuer_org[0]"
          
      - type: json
        name: subject_org
        json:
            - ".subject_org[0]"
     
      - type: json
        name: subject_an
        json:
            - ".subject_an[0]" 
