id: pipfile-config

info:
  name: Pipfile Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Pipfile configuration information was detected.
  reference: https://pypi.org/project
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    max-request: 1
    verified: true
    shodan-query: html:"Pipfile"
  tags: exposure,pip,devops,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/Pipfile"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[[source]]'
          - '[packages]'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
