id: pre-commit-config

info:
  name: Pre-commit Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Pre-commit configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  reference: https://pre-commit.com/
  metadata:
    max-request: 2
    verified: true
  tags: exposure,devops,config,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/.pre-commit-config.yaml"
      - "{{BaseURL}}/pre-commit-config.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "repos:"
          - "hooks:"
          - "rev:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
