id: product-input-fields-for-woocommerce-97004c16a7bb5fede3689ed987325810

info:
  name: >
    Product Input Fields for WooCommerce <= 1.2.6 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/01e41573-9329-48e1-9191-e8e1532f7afc?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-input-fields-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-input-fields-for-woocommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-input-fields-for-woocommerce,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-input-fields-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-input-fields-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2.6')