id: product-xml-feeds-for-woocommerce-edc5d273bbf7b8d4e9c3379e3710c137

info:
  name: >
    Product XML Feed Manager for WooCommerce <= 2.9.2 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/a054394c-07fa-4961-89f0-1d0fceac736b?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-xml-feeds-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-xml-feeds-for-woocommerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-xml-feeds-for-woocommerce,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-xml-feeds-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-xml-feeds-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.9.2')