id: prodigy-commerce-89dae14b2ed2d25b5a5c7aae20575f1c

info:
  name: >
    Prodigy Commerce <= 3.0.8 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/14b10f8e-37dd-4a34-87da-c09fdb8e09b3?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/prodigy-commerce/"
    google-query: inurl:"/wp-content/plugins/prodigy-commerce/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,prodigy-commerce,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/prodigy-commerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "prodigy-commerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.0.8')