id: prod-conf

info:
  name: Generic configuration check
  author: otterly
  severity: medium
  description: Check for certain endpoints
  metadata:
    max-request: 6
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/conf/prod/config.json"
      - "{{BaseURL}}/conf/production/config.json"
      - "{{BaseURL}}/config/prod/config.json"
      - "{{BaseURL}}/config/production/config.json"
      - "{{BaseURL}}/configuration/prod/config.json"
      - "{{BaseURL}}/configuration/production/config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"username" :'
          - '"password" :'
        condition: and
        part: body

      - type: status
        status:
          - 200
