id: product-import-export-for-woo-dff79993b1a326316fc71a31854535cf

info:
  name: >
    Product Import Export for WooCommerce <= 2.4.1 - Authenticated(Shop Manager+) Arbitrary File Upload
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/c495ac39-c99b-423d-a601-d0bfcc514ebe?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-import-export-for-woo/"
    google-query: inurl:"/wp-content/plugins/product-import-export-for-woo/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,product-import-export-for-woo,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-import-export-for-woo/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-import-export-for-woo"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.4.1')