id: prometheus-flags-endpoint

info:
  name: Prometheus flags API endpoint
  author: geeknik
  severity: info
  description: The flags endpoint provides a full path to the configuration file. If the file is stored in the home directory, it may leak a username.
  reference: https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  tags: prometheus,exposure


requests:
  - raw:
      - |
        GET /api/v1/status/flags HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"data":'
          - '"config.file":'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

    extractors:
      - type: regex
        name: web_admin_enabled
        regex:
          - '\"web\.enable\-admin\-api\"\: \"true\"'
