id: prometheus-log

info:
  name: Exposed Prometheus
  author: dhiyaneshDK,thevillagehacker
  severity: low
  description: Prometheus instance is exposed.
  metadata:
    max-request: 3
  tags: prometheus,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/prometheus"
      - "{{BaseURL}}/actuator/prometheus"
      - "{{BaseURL}}/actuator/prometheus;%2f..%2f..%2f"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'gateway_request_total'
          - 'logback_events_total'
        condition: or

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100d5a9f8ae7e3d799ea642d2eef5a277b5cf3ac5a114458911bc4cf1f4372481f5022100ff79efd4d84754d539822480473bd41470e4c493b8857bc36a514a01c9be1637:922c64590222798bb761d5b6d8e72950