id: wgetrc-config

info:
  name: Wgetrc Configuration File - Detect
  author: DhiyaneshDK
  severity: info
  description: Wgetrc configuration file was detected.
  reference: https://www.gnu.org/software/wget/manual/html_node/Wgetrc-Commands.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    max-request: 2
    verified: true
    shodan-query: html:".wgetrc"
  tags: devops,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/wgetrc"
      - "{{BaseURL}}/.wgetrc"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '/etc/wgetrc'
          - 'wget.info'

      - type: word
        part: header
        words:
          - 'application/octet-stream'

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/24
