id: wordpress-git-config2

info:
  name: Wordpress Git Config
  author: nerrorsec
  severity: info
  description: Searches for the pattern /.git/config inside themes and plugins folder.
  reference: https://hackerone.com/reports/248693
  tags: config,git,exposure,wordpress,wp-plugin,wp-theme


requests:
  - raw:
      - |
        GET /wp-content/themes/.git/config HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[core]"

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and

      - type: status
        status:
          - 200
