id: wpconfig

info:
  name: Database account information for WordPress blog leaked via txt configuration file
  author: c4sper0
  severity: High
  tags: config,backup,wordpress
    
http:
  - method: GET
    path:
      - "{{BaseURL}}/home/{{DN}}WORDPRESS.txt"
      - "{{BaseURL}}/home/{{DN}}-WORDPRESS.txt"
    
    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DB_USER"
          - "DB_PASSWORD"
          - "DB_HOST"
        part: body
        condition: and

      - type: status
        status:
          - 304
