file:
- extensions:
  - xml
  matchers:
  - condition: or
    negative: true
    type: word
    words:
    - <session_timeout>
    - <session_timeout>0</session_timeout>
  - condition: and
    type: word
    words:
    - <pfsense>
    - <webgui>
    - <system>
  matchers-condition: and
id: configure-session-timeout
info:
  author: pussycat0x
  description: 'Indefinite or even long session timeout window increase the risk of
    attackers abusing abandoned sessions.

    '
  metadata:
    verified: true
  name: Configure Sessions Timeout
  reference: 'https://docs.netgate.com/pfsense/en/latest/config/advanced-admin.html

    '
  severity: info
  tags: firewall,config,audit,pfsense,file
