id: jeecg-boot-swagger

info:
  name: Jeecg Boot Swagger Bootstrap UI - Detect
  author: ritikchaddha
  severity: info
  description: Jeecg Swagger Bootstrap UI exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Jeecg-Boot"
    fofa-query: title="JeecgBoot 企业级低代码平台"
  tags: jeecg,swagger,detect,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/jeecg-boot/"

    matchers:
      - type: word
        part: body
        words:
          - "<title>Swagger-Bootstrap-UI</title>"
# digest: 4a0a004730450220399772c6fac159e018e26aec89d85d94a9df282c1213c027e08db8b7e2f0169a022100e5952c927f759d37af355d775a184c33c49feb8ac669322d647f24700fe5d4fa:922c64590222798bb761d5b6d8e72950