id: js_composer-d41d8cd98f00b204e9800998ecf8427e

info:
  name: "WPBakery Page Builder for WordPress (formerly Visual Composer) <= 4.7.3 - Multiple Cross-Site Scripting Issues"
  author: topscoder
  severity: high
  description: "The WPBakery Page Builder for WordPress plugin for WordPress is vulnerable to Cross-Site Scripting in versions up to, and including, 4.7.3 that made it possible for attackers to inject arbitrary web scripts into pages."
  reference:

  classification:
    cvss-metrics:
    cvss-score:
    cve-id:
  metadata:
    fofa-query: "wp-content/plugins/js_composer/"
    google-query: inurl:"/wp-content/plugins/js_composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,js_composer,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/js_composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "js_composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 4.7.4')