http:
- matchers:
  - part: body
    type: word
    words:
    - <title>Swagger-Bootstrap-UI</title>
  method: GET
  path:
  - '{{BaseURL}}/jeecg-boot/'
id: jeecg-boot-swagger
info:
  author: ritikchaddha
  metadata:
    fofa-query: "title=\"JeecgBoot \u4F01\u4E1A\u7EA7\u4F4E\u4EE3\u7801\u5E73\u53F0\
      \""
    max-req: 1
    shodan-query: title:"Jeecg-Boot"
    verified: 'true'
  name: Jeecg Boot Swagger Bootstrap UI - Detect
  severity: info
  tags: jeecg,swagger,detect,exposure
