id: esphome-panel

info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: esphome
    shodan-query: title:"Login - ESPHome"
    vendor: esphome
    verified: true
  tags: panel,esphome,iot

http:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'class="esphome-header'

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100dcf24a133939ac8bd2f2b10cf2f31e4bc45953c43d7189b468beddaf5f73b343022100b9f6094572be4aac94e19038a2dbc13dc8c2aa24f0748eebd76fc1750438bc91:922c64590222798bb761d5b6d8e72950