id: saltstack-config-panel

info:
  name: SaltStack Config Panel - Detect
  author: pussycat0x
  severity: info
  description: |
    SaltStack config panel was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
    shodan-query: title:"SaltStack Config"
    verified: true
  tags: panel,vmware,login,saltstack

http:
  - method: GET
    path:
      - "{{BaseURL}}/login"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "SaltStack Config"

      - type: status
        status:
          - 200
# digest: 490a0046304402201453ccc21b26a14cd3c44aec8a9dd6136e475c8160f80155cdd7667bced98660022072fc17603dec494850f543325e3c279c40061c223971a54eb6ce14bf8c812340:922c64590222798bb761d5b6d8e72950