id: sftp-config-exposure

info:
  name: SFTP Configuration File - Detect
  author: geeknik
  severity: high
  description: SFTP configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  reference:
    - https://blog.sucuri.net/2012/11/psa-sftpftp-password-exposure-via-sftp-config-json.html
    - https://www.acunetix.com/vulnerabilities/web/sftp-ftp-credentials-exposure/
    - https://codexns.io/products/sftp_for_sublime/settings
  metadata:
    max-request: 1
    verified: true
    github-query: filename:sftp-config.json
  tags: sftp,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/sftp-config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"host":'
          - '"user":'
          - '"password":'
          - '"remote_path":'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/03/02
