id: sonic-wall-application

info:
  name: SonicWall Appliance Management Console Login Panel - Detect
  author: DhiyaneshDk,Tess
  severity: info
  description: SonicWall Appliance Management Console login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:o:sonicwall:sma1000_firmware:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: sma1000_firmware
    shodan-query: title:"Appliance Management Console Login"
    vendor: sonicwall
    verified: true
  tags: panel,sonicwall,login

http:
  - method: GET
    path:
      - "{{BaseURL}}/login.do"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Appliance Management Console Login</title>'

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100c721d633a1901f7c1495a267826fa0017c87d861fb4f5f46e6e5b25dc90e6a5e022036d212c4ffeea8083bdc6bb1b9ee372dfeba336adbc3a3ebca41fdc916be2bad:922c64590222798bb761d5b6d8e72950