id: swagger-panel

info:
  name: Swagger API Panel
  author: Ice3man
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api-docs/swagger.json"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.json"
    matchers:
      - type: word
        words:
          - "\"swagger\":"
          - "Swagger UI"
        condition: or
