id: 1003-mortgage-application-57412bd5e68fb88be6080778434b3c2c

info:
  name: >
    1003 Mortgage Application <= 1.75 - Unauthenticated CSV Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/63567094-9fb1-44b2-a3e6-99194389c4b6?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/1003-mortgage-application/"
    google-query: inurl:"/wp-content/plugins/1003-mortgage-application/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,1003-mortgage-application,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/1003-mortgage-application/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "1003-mortgage-application"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.75')