http:
- extractors:
  - group: 1
    name: version
    part: body
    regex:
    - (?mi)Stable tag:\s*([0-9.]+)
    type: regex
  matchers:
  - status:
    - 200
    type: status
  - part: body
    type: word
    words:
    - blog-settings
  - dsl:
    - compare_versions(version, '<= 1.0')
    type: dsl
  matchers-condition: and
  max-redirects: 3
  method: GET
  path:
  - '{{BaseURL}}/wp-content/plugins/blog-settings/readme.txt'
  redirects: true
id: blog_settings-d28e5374-dd34-4745-a20b-059e9846d96d
info:
  author: topscoder
  classification:
    cve-id: null
    cvss-metrics: null
    cvss-score: null
  description: ''
  metadata:
    fofa-query: wp-content/plugins/blog-settings/
    google-query: inurl:"/wp-content/plugins/blog-settings/"
    shodan-query: http.html:"wp-content/plugins/blog-settings/"
  name: 'Blog Settings <= 1.0 - Reflected Cross-Site Scripting via ''page'' Parameter

    '
  reference:
  - https://github.com/topscoder/nuclei-wordfence-cve
  - https://www.wordfence.com/threat-intel/vulnerabilities/id/d28e5374-dd34-4745-a20b-059e9846d96d?source=api-scan
  severity: medium
  tags: cve,wordpress,wp-plugin,blog-settings,medium,candidate
