id: tinymce-extended-config-fec13fcda8eb68de45c88475321ae39d

info:
  name: >
    TinyMCE Extended Config <= 0.1.0 - Reflected Cross-Site Scripting
  author: topscoder
  severity: medium
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/82f525c9-c032-4770-8424-4ab7e05784f4?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/tinymce-extended-config/"
    google-query: inurl:"/wp-content/plugins/tinymce-extended-config/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,tinymce-extended-config,medium

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/tinymce-extended-config/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "tinymce-extended-config"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 0.1.0')