id: travis-ci-disclosure

info:
  name: Travis CI Disclosure
  author: 0xr2r
  severity: high
  description: Travis CI is a Software as a Service (SaaS) based continuous integration service used to build and test software projects. By defining a configuration file named `.travis.yml` in their source code repositories, developers can customize their applications build workflows.
  tags: config, secrets, leaks, cheatset, tokens, sql, tokens

requests:
  - method: GET
    path:
      - '{{BaseURL}}/.travis.yml'
      - '{{BaseURL}}/travis.yml'
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - 'language:'
          - 'DOCKER_MYSQL_TYPE'
          - 'MYSQL_ROOT_PASSWORD='


          

