id: openapi1

info:
  name: OpenAPI
  author: pdteam
  severity: info
  tags: exposure,api


requests:
  - raw:
      - |
        GET /openapi.json HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "application/openapi+json"
          - "application/json"
        condition: or
        part: header
      - type: word
        words:
          - servers
          - paths
        condition: and
      - type: status
        status:
          - 200
