id: keycloak-admin-console-config
info:
  name: Keycloak Admin Console Configuration Disclosure
  author: 0x_Akoko
  severity: low
  description: |
    Detected Keycloak admin console configuration was exposing realm name, client ID, SSL requirements, and authentication server URL enabling reconnaissance and targeted authentication attacks.
  reference:
    - https://www.keycloak.org/docs/latest/server_admin/index.html
    - https://www.keycloak.org/docs/latest/securing_apps/index.html
  metadata:
    runzero-match: service["product"] contains "RedHat:Keycloak"
    max-request: 4
    shodan-query: app:"Keycloak"
    verified: true
  tags: config,disclosure,exposure,keycloak,vuln
http:
  - matchers:
      - condition: and
        part: body
        type: word
        words:
          - '"realm":'
          - '"resource":'
          - '"auth-server-url":'
      - part: content_type
        type: word
        words:
          - application/json
      - status:
          - 200
        # digest: 4b0a00483046022100cad3ca53655112b2211ee5375e81f53a9d3d448d9761d51ac194581986de00e2022100c7ff6ca8abcd680a5ad3e85271a69d4416f30075501cb97c6edd2b11faa211ae:922c64590222798bb761d5b6d8e72950

        type: status
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}/admin/master/console/config'
      - '{{BaseURL}}/admin/main/console/config'
      - '{{BaseURL}}/auth/admin/master/console/config'
      - '{{BaseURL}}/auth/admin/main/console/config'
    stop-at-first-match: true
