id: kingcomposer-cee657e0bb3c97b5804e9d7bcf12fa17

info:
  name: >
    Page Builder: KingComposer – Free Drag and Drop page builder by King-Theme <= 2.9.4 - Reflected Cross-Site Scripting
  author: topscoder
  severity: medium
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/d52cdc45-efea-46b5-9004-f3169e807747?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/kingcomposer/"
    google-query: inurl:"/wp-content/plugins/kingcomposer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,kingcomposer,medium

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/kingcomposer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "kingcomposer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.9.4')