id: default-oracle-application-page

info:
  name: Oracle Application Server Containers
  author: dhiyaneshDk
  severity: info
  metadata:
    max-request: 1
    shodan-query: http.title:"Oracle Application Server Containers"
  tags: tech,oracle

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - "<TITLE>Oracle Application Server Containers for J2EE 10g</TITLE>"
        part: body

# digest: 4b0a00483046022100b5780eb561a58f9d667836c535ca4bb787b2a83dab8870ef6e82a6760499f5ab022100f615f1b3ea1b9d9096cf240a0920aeab2287005c10cfe2b5241c9be736cb424b:922c64590222798bb761d5b6d8e72950
