id: deployment-ini

info:
  name: FTP Deployment Config File - Exposure
  author: Michal Mikolas (nanuqcz)
  severity: medium
  description: |
    Config file for "FTP deployment" utility usually contains server's FTP credentials in plain text.
  remediation: |
     Delete the config file from server & add it to `ignore` section of the deployment file. Or block access to the file using `.htaccess` on the server.
  reference:
    - https://github.com/dg/ftp-deployment
  metadata:
    vendor: dg
    product: ftp-deployment
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/deployment.ini"
      - "{{BaseURL}}/deploy.ini"
      - "{{BaseURL}}/production.ini"
      - "{{BaseURL}}/prod.ini"
      - "{{BaseURL}}/deployment.production.ini"
      - "{{BaseURL}}/deployment.prod.ini"
      - "{{BaseURL}}/deploy.production.ini"
      - "{{BaseURL}}/deploy.prod.ini"
      - "{{BaseURL}}/server.ini"
      - "{{BaseURL}}/ftp.ini"
      - "{{BaseURL}}/ftps.ini"
      - "{{BaseURL}}/sftp.ini"

    stop-at-first-match: true

    matchers:
      - type: regex
        regex:
          - "^remote\\s*=\\s*"
          - '^\[(.*?)\]$'
        condition: and
# digest: 490a00463044022006ca25aa98e2a16f9c23375cf69c8f0f211f2ef3b2eafa8c35a78a5ed657f21802207310041408348fe3fee737201869053caa5ae93ca230810d0410fa9c39c8da5a:922c64590222798bb761d5b6d8e72950