id: grandstream-device-configuration

info:
  name: Grandstream Device Configuration
  author: dhiyaneshDK
  severity: info
  description: Exposed Grandstream device configuration page detected.
  metadata:
    max-request: 1
    shodan-query: http.title:"Grandstream Device Configuration"
  tags: iot

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Grandstream Device Configuration</title>'

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c1185f8d776754c9a70431024fd52aa8d0eda89e1add045809bcc28ca4a673c0022100c3c467a3ce2d09fc8fec4b3b803dc3b69a656094debd6fc13f7dd48612f8dc69:922c64590222798bb761d5b6d8e72950