id: redis-config

info:
  name: Redis Configuration File - Detect
  author: geeknik
  severity: medium
  description: Redis configuration file was detected.
  reference:
    - https://redis.io/docs/manual/config/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
    verified: true
    shodan-query: html:"redis.conf"
  tags: redis,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/redis.conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "bind"
          - "protected-mode"
          - "port "
        condition: and

      - type: word
        part: header
        words:
          - "application/octet-stream"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
