id: rubocop-config

info:
  name: Rubocop Configuration - Detect
  author: DhiyaneshDk
  severity: info
  description: Rubocop configuration information was detected.
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
    - https://github.com/rubocop/rubocop
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    max-request: 1
    verified: true
    shodan-query: html:"rubocop.yml"
  tags: exposure,files,config,ruby

http:
  - method: GET
    path:
      - '{{BaseURL}}/.rubocop.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "AllCops:"
          - "Include:"
          - "Exclude:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
