id: netlify-takeover

info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  severity: high
  description: netlify takeover was detected.
  reference:
    - https://github.com/EdOverflow/can-i-take-over-xyz/issues/40
    - https://monish-basaniwal.medium.com/how-i-found-my-first-subdomain-takeover-vulnerability-b7d5c17b61fd
    - https://github.com/EdOverflow/can-i-take-over-xyz/pull/289
  metadata:
    max-request: 1
  tags: takeover,netlify

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - Host != ip

      - type: word
        part: body
        words:
          - "Not Found - Request ID:"
        case-insensitive: true

      - type: word
        part: header
        words:
          - "Netlify"
# digest: 4a0a004730450221009a5a121d786fe47e6abfdf7b52f451237d696d19fa9df212b83dab270e03509b0220481f0dfdf70ae43cf23a05b969ad56aedcbb2f3f202d208b5b911e54342eb00c:922c64590222798bb761d5b6d8e72950